//! The animal names a Send Plugin is given when it has no typed or track name.
//! Short, distinct and easy to say.

pub const ANIMALS: [&str; 100] = [
    "Aardvark",
    "Albatross",
    "Alpaca",
    "Anteater",
    "Antelope",
    "Armadillo",
    "Axolotl",
    "Badger",
    "Barracuda",
    "Bat",
    "Beaver",
    "Bison",
    "Bobcat",
    "Buffalo",
    "Camel",
    "Capybara",
    "Caribou",
    "Cheetah",
    "Chinchilla",
    "Cobra",
    "Condor",
    "Cougar",
    "Coyote",
    "Crane",
    "Crow",
    "Deer",
    "Dingo",
    "Dolphin",
    "Donkey",
    "Dove",
    "Eagle",
    "Eel",
    "Elephant",
    "Elk",
    "Emu",
    "Falcon",
    "Ferret",
    "Finch",
    "Flamingo",
    "Fox",
    "Frog",
    "Gazelle",
    "Gecko",
    "Gibbon",
    "Giraffe",
    "Gnu",
    "Goat",
    "Gorilla",
    "Hare",
    "Hawk",
    "Hedgehog",
    "Heron",
    "Hippo",
    "Hyena",
    "Ibex",
    "Ibis",
    "Iguana",
    "Jackal",
    "Jaguar",
    "Jay",
    "Kangaroo",
    "Kestrel",
    "Kiwi",
    "Koala",
    "Lemur",
    "Leopard",
    "Llama",
    "Lobster",
    "Lynx",
    "Magpie",
    "Manatee",
    "Marmot",
    "Meerkat",
    "Mink",
    "Mole",
    "Moose",
    "Narwhal",
    "Newt",
    "Ocelot",
    "Octopus",
    "Okapi",
    "Orca",
    "Osprey",
    "Ostrich",
    "Otter",
    "Owl",
    "Panda",
    "Panther",
    "Parrot",
    "Pelican",
    "Penguin",
    "Puffin",
    "Quail",
    "Raccoon",
    "Raven",
    "Seal",
    "Sloth",
    "Tapir",
    "Walrus",
    "Wombat",
];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn animals_are_distinct() {
        let mut sorted = ANIMALS.to_vec();
        sorted.sort_unstable();
        sorted.dedup();
        assert_eq!(sorted.len(), ANIMALS.len());
    }
}
